# .github/workflows/sync-develop-to-master.yml
name: Sync develop to master

on:
  push:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 過去の履歴も取得

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync develop into master
        run: |
          git checkout master
          git merge origin/develop --no-ff -m "chore: sync develop into master"
          git push origin master
